Adding a template for change plan requests/proposals.
drud/community pull request #2
Opened 2017-03-20 19:14 UTC by TopherGopher

2017-03-20 20:57 UTC, cyberswat commented
This is in response to https://github.com/drud/aws-infra/issues/8 ... The purpose of the ticket is to provide a community based template that we can refer people to when they would like to initiate change.

2017-03-20 22:22 UTC, cyberswat commented on development/proposal_template.md
> +### The Ideal Situation
This should probably not be repeated. Same with The Proposed Solution

2017-03-20 22:23 UTC, cyberswat requested changes

2017-03-20 22:23 UTC, cyberswat commented on development/proposal_template.md
> +### Managing the Project
We don't want people considering people and budget.  We want them to consider timelines of major pieces, but it's probably too much to ask for more.

2017-03-21 01:18 UTC, TopherGopher commented
I have combined a few sections and removed references to things such as cost and team members. See if you like what I did.

2017-03-21 15:28 UTC, cyberswat requested changes

2017-03-21 15:28 UTC, cyberswat commented on development/proposal_template.md
> +## The Current Situation
This looks like it was copied out of a pdf.  It needs to be written from our perspective using our words.

2017-03-21 17:27 UTC, cyberswat commented
This should be resolved by #4

2017-03-21 17:27 UTC, closed without merging